// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 3EaMA65xrPs96BzDRgA4Kb
// Component: t-etfb9JiAudE
import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";

import * as p from "@plasmicapp/react-web";
import * as ph from "@plasmicapp/host";

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic_fred_financial.module.css"; // plasmic-import: 3EaMA65xrPs96BzDRgA4Kb/projectcss
import sty from "./PlasmicBderWhite.module.css"; // plasmic-import: t-etfb9JiAudE/css

export type PlasmicBderWhite__VariantMembers = {};

export type PlasmicBderWhite__VariantsArgs = {};
type VariantPropType = keyof PlasmicBderWhite__VariantsArgs;
export const PlasmicBderWhite__VariantProps = new Array<VariantPropType>();

export type PlasmicBderWhite__ArgsType = {};
type ArgPropType = keyof PlasmicBderWhite__ArgsType;
export const PlasmicBderWhite__ArgProps = new Array<ArgPropType>();

export type PlasmicBderWhite__OverridesType = {
  root?: p.Flex<"div">;
};

export interface DefaultBderWhiteProps {
  className?: string;
}

function PlasmicBderWhite__RenderFunc(props: {
  variants: PlasmicBderWhite__VariantsArgs;
  args: PlasmicBderWhite__ArgsType;
  overrides: PlasmicBderWhite__OverridesType;

  forNode?: string;
}) {
  const { variants, args, overrides, forNode } = props;

  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        projectcss.plasmic_tokens,
        sty.root
      )}
    />
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  typeof PlasmicDescendants[T][number];
type NodeDefaultElementType = {
  root: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicBderWhite__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicBderWhite__VariantsArgs;
    args?: PlasmicBderWhite__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicBderWhite__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicBderWhite__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicBderWhite__ArgProps,
      internalVariantPropNames: PlasmicBderWhite__VariantProps
    });

    return PlasmicBderWhite__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicBderWhite";
  } else {
    func.displayName = `PlasmicBderWhite.${nodeName}`;
  }
  return func;
}

export const PlasmicBderWhite = Object.assign(
  // Top-level PlasmicBderWhite renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements

    // Metadata about props expected for PlasmicBderWhite
    internalVariantProps: PlasmicBderWhite__VariantProps,
    internalArgProps: PlasmicBderWhite__ArgProps
  }
);

export default PlasmicBderWhite;
/* prettier-ignore-end */
